openapi: 3.0.1
info:
  title: Preschool API
  description: API specification
  version: 1.0.0

paths:
  #ChildAPI
  /child:
    post:
      summary: Saving new child
      operationId: saveChild
      tags:
        - child
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChildResource'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64
    get:
      summary: Reading all children
      operationId: getAllChildren
      tags:
        - child
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildResource'

  /child/{caregiverId}:
    get:
      summary: Reading all children by caregiver
      operationId: getAllChildrenByCaregiver
      tags:
        - child
      parameters:
        - in: path
          name: caregiverId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildResource'

  /child/caregiver/{caregiverId}/{childId}:
    post:
      summary: Saving new child
      operationId: saveChildByCaregiver
      tags:
        - child
      parameters:
        - in: path
          name: caregiverId
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: childId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64

  #EducatorAPI
  /educator:
    post:
      summary: Saving new educator
      operationId: saveEducator
      tags:
        - educator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EducatorResource'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64
    get:
      summary: Reading all educators
      operationId: getAllEducators
      tags:
        - educator
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EducatorResource'

  /educator/{educatorId}:
    get:
      summary: Reading educator
      operationId: getEducator
      tags:
        - educator
      parameters:
        - in: path
          name: educatorId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EducatorResource'

  /educator/children/{groupId}:
    get:
      summary: Reading children in group
      operationId: educatorGetChildrenInGroup
      tags:
        - educator
        - children
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildResource'

  /educator/child/{childId}:
    get:
      summary: Reading child
      operationId: educatorGetChild
      tags:
        - educator
        - child
      parameters:
        - in: path
          name: childId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChildResource'

  /educator/absence/{childId}/{date}/{reason}:
    get:
      summary: Saving absence
      operationId: educatorSaveAbsence
      tags:
        - educator
        - attendance
      parameters:
        - in: path
          name: childId
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: date
          schema:
            type: string
          required: true
        - in: path
          name: reason
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64

  /educator/absence/{groupId}:
    get:
      summary: Reading all absences in group
      operationId: getAbsences
      tags:
        - educator
        - attendance
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceResource'

  /educator/present/{groupId}:
    get:
      summary: Reading all present in group
      operationId: getPresent
      tags:
        - educator
        - attendance
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceResource'

  #CaregiverAPI
  /caregiver:
    get:
      summary: Reading all caregivers
      operationId: getAllCaregivers
      tags:
        - caregiver
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaregiverResource'

  /caregiver/{caregiverId}:
    get:
      summary: Reading caregiver
      operationId: getCaregiver
      tags:
        - caregiver
      parameters:
        - in: path
          name: caregiverId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaregiverResource'

  /caregiver/child/{childId}:
    get:
      summary: Reading child
      operationId: caregiverGetChild
      tags:
        - caregiver
        - child
      parameters:
        - in: path
          name: childId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChildResource'

  /caregiver/upsert-caring-time/{childId}:
    put:
      summary: Upserting caring time
      operationId: upsertCaringTime
      tags:
        - caregiver
        - child
        - caringTime
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaringTimeResource'
      parameters:
        - in: path
          name: childId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64

  /caregiver/educator/{groupId}:
    get:
      summary: Get all educators in group
      operationId: getEducatorsInGroup
      tags:
        - caregiver
        - educator
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EducatorResource'

  /caregiver/absence/{childId}/{date}/{reason}:
    get:
      summary: Saving absence
      operationId: caregiverSaveAbsence
      tags:
        - caregiver
        - attendance
      parameters:
        - in: path
          name: childId
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: date
          schema:
            type: string
          required: true
        - in: path
          name: reason
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64

  # Login API
  /login/{userName}/{password}:
    get:
      summary: Log in
      operationId: logIn
      tags:
        - login
      parameters:
        - in: path
          name: userName
          schema:
            type: string
          required: true
        - in: path
          name: password
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64

components:
  schemas:

    ZipCodeResource:
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string

    CityResource:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string


    PersonalInformationResource:
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        personalNumber:
          type: string
        address:
          type: string
        zipCode:
          $ref: '#/components/schemas/ZipCodeResource'
        city:
          $ref: '#/components/schemas/CityResource'

    ContactInformationResource:
      properties:
        id:
          type: integer
          format: int64
        phoneNumber:
          type: string
        email:
          type: string

    GroupTypeResource:
      properties:
        id:
          type: integer
          format: int64
        groupType:
          type: string

    WeekdayResource:
      properties:
        id:
          type: integer
          format: int64
        weekday:
          type: string

    PreschoolGroupResource:
      properties:
        id:
          type: integer
          format: int64
        groupType:
          $ref: '#/components/schemas/GroupTypeResource'
        name:
          type: string
        places:
          type: integer

    CaregiverResource:
      properties:
        id:
          type: integer
          format: int64
        personalInformation:
          $ref: '#/components/schemas/PersonalInformationResource'
        contactInformation:
          $ref: '#/components/schemas/ContactInformationResource'
        security:
          $ref: '#/components/schemas/SecurityResource'

    ChildResource:
      properties:
        id:
          type: integer
          format: int64
        personalInformation:
          $ref: '#/components/schemas/PersonalInformationResource'
        preschoolGroup:
          $ref: '#/components/schemas/PreschoolGroupResource'
        caregivers:
          type: array
          items:
            $ref: '#/components/schemas/CaregiverResource'
        caringTimes:
          type: array
          items:
            $ref: '#/components/schemas/CaringTimeResource'
        relatives:
          type: array
          items:
            $ref: '#/components/schemas/RelativeResource'

    RelativeResource:
      properties:
        id:
          type: integer
          format: int64
        contactInformation:
          $ref: '#/components/schemas/ContactInformationResource'
        firstName:
          type: string
        lastName:
          type: string
        relationToChild:
          type: string

    EducatorResource:
      properties:
        id:
          type: integer
          format: int64
        personalInformation:
          $ref: '#/components/schemas/PersonalInformationResource'
        contactInformation:
          $ref: '#/components/schemas/ContactInformationResource'
        security:
          $ref: '#/components/schemas/SecurityResource'
        preschoolGroup:
          $ref: '#/components/schemas/PreschoolGroupResource'
        isAdmin:
          type: boolean

    CaringTimeResource:
      properties:
        id:
          type: integer
          format: int64
        weekday:
          type: string
        startHour:
          type: string
        startMinut:
          type: string
        endHour:
          type: string
        endMinut:
          type: string

    SecurityResource:
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
        password:
          type: string

    AttendanceResource:
      properties:
        id:
          type: integer
          format: int64
        child:
          $ref: '#/components/schemas/ChildResource'
        date:
          type: string
          format: date
        isPresent:
          type: boolean
        reasonToAbsence:
          type: string