openapi: 3.0.1
info:
  title: Preschool API
  description: API specification
  version: 1.0.0

paths:
  /child:
    post:
      summary: Saving new child
      operationId: saveChild
      tags:
        - child
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChildResource'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64
    get:
      summary: Reading all children
      operationId: getAllChildren
      tags:
        - child
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildResource'

  /child/{childId}:
    get:
      summary: Reading child
      operationId: getChild
      tags:
        - child
      parameters:
        - in: path
          name: childId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChildResource'

  /child/group/{groupId}:
    get:
      summary: Reading children in group
      operationId: getChildrenInGroup
      tags:
        - child
      parameters:
        - in: path
          name: groupId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChildResource'

components:
  schemas:

    ZipCodeResource:
      properties:
        number:
          type: string

    CityResource:
      properties:
        name:
          type: string


    PersonalInformationResource:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        personalNumber:
          type: string
        address:
          type: string
        zipCode:
          $ref: '#/components/schemas/ZipCodeResource'
        city:
          $ref: '#/components/schemas/CityResource'

    ContactInformationResource:
      properties:
        phoneNumber:
          type: string
        email:
          type: string

    GroupTypeResource:
      properties:
        groupType:
          type: string

    WeekdayResource:
      properties:
        weekday:
          type: string

    PreschoolGroupResource:
      properties:
        groupType:
          $ref: '#/components/schemas/GroupTypeResource'
        name:
          type: string
        places:
          type: integer

    CaregiverResource:
      properties:
        personalInformation:
          $ref: '#/components/schemas/PersonalInformationResource'
        contactInformation:
          $ref: '#/components/schemas/ContactInformationResource'
        security:
          $ref: '#/components/schemas/SecurityResource'

    ChildResource:
      properties:
        personalInformation:
          $ref: '#/components/schemas/PersonalInformationResource'
        preschoolGroup:
          $ref: '#/components/schemas/PreschoolGroupResource'
        caregivers:
          type: array
          items:
            $ref: '#/components/schemas/CaregiverResource'
        caringTimes:
          type: array
          items:
            $ref: '#/components/schemas/CaringTimeResource'
        relatives:
          type: array
          items:
            $ref: '#/components/schemas/RelativeResource'

    RelativeResource:
      properties:
        contactInformation:
          $ref: '#/components/schemas/ContactInformationResource'
        firstName:
          type: string
        lastName:
          type: string
        relationToChild:
          type: string

    Educator:
      properties:
        personalInformation:
          $ref: '#/components/schemas/PersonalInformationResource'
        contactInformation:
          $ref: '#/components/schemas/ContactInformationResource'
        security:
          $ref: '#/components/schemas/SecurityResource'
        preschoolGroup:
          $ref: '#/components/schemas/PreschoolGroupResource'
        isAdmin:
          type: boolean

    CaringTimeResource:
      properties:
        weekday:
          type: string
        startHour:
          type: integer
        startMinut:
          type: integer
        endHour:
          type: integer
        endMinut:
          type: integer

    SecurityResource:
      properties:
        userName:
          type: string
        password:
          type: string

    Attendance:
      properties:
        child:
          $ref: '#/components/schemas/ChildResource'
        date:
          type: string
          format: date-time
        isPresent:
          type: boolean